# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7158e92b4f07bd6fe1acf2467ae7bcee052edf85699966e6f7d86327b175f8cbe3329653fd2c46ba1a215473064b02de3fbd6f020fffe569af64a8b3148f9cf9

test:
  secret_key_base: aaeaf920eb3df97d356325888abf167fb531b6764739bc41e180d750c485a87cc21b7aa76852f4d4080146f0370785f485a463a9a7eb2c293fc65b467d73163f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
